"""
Insurance Policy Knowledge Base Seed Dataset.
Curated strictly from the 5 provided reference documents:
1. 2 YEAR & Permanent Exclusion-2.pdf (14 2-Year Waiting Periods & 32 Permanent Exclusions)
2. Leaflet artwork.pdf & Mail - ClaimSupport 2.pdf (Niva Bupa ReAssure 3.0 Specifications & 4 Variants)
3. Snapshot.pdf & Mail - ClaimSupport 1.pdf (Market Share & Solvency Benchmark)
"""

from datetime import datetime, timezone

NOW_UTC = datetime(2026, 1, 1, tzinfo=timezone.utc)

# ──────────────────────────────────────────────────────────────────────────────
# 1. Insurance Companies Dataset
# ──────────────────────────────────────────────────────────────────────────────
SEED_COMPANIES = [
    {
        "companyId": "INS-NIVA-BUPA",
        "name": "Niva Bupa Health Insurance Company Limited",
        "code": "NIVA_BUPA",
        "category": "Standalone Health Insurer (SAHI)",
        "marketRank": 3,
        "marketSharePct": 3.0,
        "solvencyRatio": 1.76,
        "solvencyStatus": "Healthy",
        "isActive": True,
        "metadata": {
            "source": "Marsh India / GIC Council Industry Snapshot (Apr-Jul 2026)",
            "healthSegmentPremiumCr": 2965,
            "growthRatePct": 32.0,
        },
    },
    {
        "companyId": "INS-NEW-INDIA",
        "name": "The New India Assurance Co Ltd",
        "code": "NIA",
        "category": "Public General Insurer",
        "marketRank": 1,
        "marketSharePct": 14.0,
        "solvencyRatio": 1.84,
        "solvencyStatus": "Healthy",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 9142, "growthRatePct": 4.0},
    },
    {
        "companyId": "INS-ICICI-LOMBARD",
        "name": "ICICI Lombard General Insurance Co Ltd",
        "code": "ICICI_LOMBARD",
        "category": "Private General Insurer",
        "marketRank": 2,
        "marketSharePct": 9.0,
        "solvencyRatio": 2.70,
        "solvencyStatus": "Robust",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 3811, "growthRatePct": 5.0},
    },
    {
        "companyId": "INS-STAR-HEALTH",
        "name": "Star Health & Allied Insurance Co Ltd",
        "code": "STAR_HEALTH",
        "category": "Standalone Health Insurer (SAHI)",
        "marketRank": 1,
        "marketSharePct": 5.0,
        "solvencyRatio": 1.82,
        "solvencyStatus": "Healthy",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 6048, "growthRatePct": 19.0},
    },
    {
        "companyId": "INS-CARE",
        "name": "Care Health Insurance Ltd",
        "code": "CARE",
        "category": "Standalone Health Insurer (SAHI)",
        "marketRank": 2,
        "marketSharePct": 3.0,
        "solvencyRatio": 1.82,
        "solvencyStatus": "Healthy",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 4009, "growthRatePct": 42.0},
    },
    {
        "companyId": "INS-TATA-AIG",
        "name": "Tata AIG General Insurance Co Ltd",
        "code": "TATA_AIG",
        "category": "Private General Insurer",
        "marketRank": 4,
        "marketSharePct": 7.0,
        "solvencyRatio": 1.91,
        "solvencyStatus": "Healthy",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 2517, "growthRatePct": 31.0},
    },
    {
        "companyId": "INS-HDFC-ERGO",
        "name": "HDFC ERGO General Insurance Co Ltd",
        "code": "HDFC_ERGO",
        "category": "Private General Insurer",
        "marketRank": 8,
        "marketSharePct": 5.0,
        "solvencyRatio": 2.07,
        "solvencyStatus": "Robust",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 2708, "growthRatePct": 20.0},
    },
    {
        "companyId": "INS-UNITED-INDIA",
        "name": "United India Insurance Co Ltd",
        "code": "UNITED_INDIA",
        "category": "Public General Insurer",
        "marketRank": 3,
        "marketSharePct": 7.0,
        "solvencyRatio": -1.36,
        "solvencyStatus": "Stressed",
        "isActive": True,
        "metadata": {"healthSegmentPremiumCr": 3651, "growthRatePct": 9.0},
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# 2. Products Dataset
# ──────────────────────────────────────────────────────────────────────────────
SEED_PRODUCTS = [
    {
        "productId": "PROD-NB-REASSURE-3",
        "companyName": "Niva Bupa Health Insurance Company Limited",
        "name": "ReAssure 3.0",
        "productType": "Comprehensive Health Insurance",
        "description": "Truly unlimited health insurance plan offering unlimited sum insured from day 1, zero capping on claims or claim amount.",
        "currentVersion": "3.0",
        "isActive": True,
        "metadata": {
            "sourceDocument": "Leaflet artwork.pdf",
            "cashlessHospitalLink": "https://rules.nivabupa.com/hospital-network/",
        },
    }
]

# ──────────────────────────────────────────────────────────────────────────────
# 3. Product Variants Dataset (Classic, Select, Elite, Black)
# ──────────────────────────────────────────────────────────────────────────────
SEED_VARIANTS = [
    {
        "variantId": "VAR-NB-R3-CLASSIC",
        "productId": "PROD-NB-REASSURE-3",
        "productName": "ReAssure 3.0",
        "companyName": "Niva Bupa Health Insurance Company Limited",
        "name": "Classic",
        "description": "Essential ReAssure 3.0 tier with General Room and standardized sub-limits.",
        "roomCategory": "General room",
        "roadAmbulanceLimit": "INR 2,000 per Hospitalization",
        "airAmbulanceLimit": "Not Covered (NA)",
        "modernTreatmentLimit": "Covered up to INR 1 Lac for each complete claim amount",
        "lockTheClock": False,
        "personalAccidentOptional": "Up to INR 10 Lacs",
        "hospitalDailyCashOptional": "INR 1,000 per day, Maximum 30 days in a year",
        "borderlessOptional": "Not Available (NA)",
        "isActive": True,
        "features": {
            "baseSumInsured": "Unlimited from Day 1",
            "carryForwardSumInsured": "Unlimited Sum Insured from Day 1",
            "useAndGetBack": "Unlimited Sum Insured from Day 1",
            "day1PED": "30 Illnesses",
            "minHospitalizationHours": 2,
            "nonPayableItems": "All 4 Non-Payable Item Lists Covered",
            "exclusiveOneMembership": True,
        },
    },
    {
        "variantId": "VAR-NB-R3-SELECT",
        "productId": "PROD-NB-REASSURE-3",
        "productName": "ReAssure 3.0",
        "companyName": "Niva Bupa Health Insurance Company Limited",
        "name": "Select",
        "description": "Popular ReAssure 3.0 tier offering Twin Sharing room, Lock the Clock, and Air Ambulance.",
        "roomCategory": "Twin Sharing room",
        "roadAmbulanceLimit": "Up to Sum Insured",
        "airAmbulanceLimit": "INR 5 Lacs per Hospitalization",
        "modernTreatmentLimit": "Up to Sum Insured",
        "lockTheClock": True,
        "personalAccidentOptional": "Up to INR 20 Lacs",
        "hospitalDailyCashOptional": "INR 2,000 per day, Maximum 30 days in a year",
        "borderlessOptional": "Up to INR 10 Lacs",
        "isActive": True,
        "features": {
            "baseSumInsured": "Unlimited from Day 1",
            "carryForwardSumInsured": "Unlimited Sum Insured from Day 1",
            "useAndGetBack": "Unlimited Sum Insured from Day 1",
            "day1PED": "30 Illnesses",
            "minHospitalizationHours": 2,
            "nonPayableItems": "All 4 Non-Payable Item Lists Covered",
            "exclusiveOneMembership": True,
        },
    },
    {
        "variantId": "VAR-NB-R3-ELITE",
        "productId": "PROD-NB-REASSURE-3",
        "productName": "ReAssure 3.0",
        "companyName": "Niva Bupa Health Insurance Company Limited",
        "name": "Elite",
        "description": "High-tier ReAssure 3.0 plan covering all rooms except Deluxe/Suite with global borderless up to 50L.",
        "roomCategory": "All rooms except Deluxe/Suite",
        "roadAmbulanceLimit": "Up to Sum Insured",
        "airAmbulanceLimit": "INR 5 Lacs per Hospitalization",
        "modernTreatmentLimit": "Up to Sum Insured",
        "lockTheClock": True,
        "personalAccidentOptional": "Up to INR 50 Lacs",
        "hospitalDailyCashOptional": "INR 4,000 per day, Maximum 30 days in a year",
        "borderlessOptional": "Up to INR 50 Lacs",
        "isActive": True,
        "features": {
            "baseSumInsured": "Unlimited from Day 1",
            "carryForwardSumInsured": "Unlimited Sum Insured from Day 1",
            "useAndGetBack": "Unlimited Sum Insured from Day 1",
            "day1PED": "30 Illnesses",
            "minHospitalizationHours": 2,
            "nonPayableItems": "All 4 Non-Payable Item Lists Covered",
            "exclusiveOneMembership": True,
        },
    },
    {
        "variantId": "VAR-NB-R3-BLACK",
        "productId": "PROD-NB-REASSURE-3",
        "productName": "ReAssure 3.0",
        "companyName": "Niva Bupa Health Insurance Company Limited",
        "name": "Black",
        "description": "Prestige ReAssure 3.0 tier offering Any Room with zero restriction, ₹1 Cr PA, and ₹5 Cr global cover.",
        "roomCategory": "All rooms (Any room with zero capping)",
        "roadAmbulanceLimit": "Up to Sum Insured",
        "airAmbulanceLimit": "INR 5 Lacs per Hospitalization",
        "modernTreatmentLimit": "Up to Sum Insured",
        "lockTheClock": True,
        "personalAccidentOptional": "Up to INR 1 Crore",
        "hospitalDailyCashOptional": "INR 4,000 per day, Maximum 30 days in a year",
        "borderlessOptional": "Up to INR 5 Crore",
        "isActive": True,
        "features": {
            "baseSumInsured": "Unlimited from Day 1",
            "carryForwardSumInsured": "Unlimited Sum Insured from Day 1",
            "useAndGetBack": "Unlimited Sum Insured from Day 1",
            "day1PED": "30 Illnesses",
            "minHospitalizationHours": 2,
            "nonPayableItems": "All 4 Non-Payable Item Lists Covered",
            "exclusiveOneMembership": True,
        },
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# 4. Policy Version Dataset
# ──────────────────────────────────────────────────────────────────────────────
SEED_VERSIONS = [
    {
        "versionId": "VER-NB-R3-2026-01",
        "productId": "PROD-NB-REASSURE-3",
        "productName": "ReAssure 3.0",
        "versionNumber": "2026.01",
        "effectiveFrom": datetime(2026, 1, 1, tzinfo=timezone.utc),
        "effectiveTo": None,
        "isCurrent": True,
        "changeSummary": "Initial baseline knowledge release covering ReAssure 3.0 4 tiers, 14 2-year waiting periods, and 32 permanent exclusions.",
        "sourceDocuments": [
            {"name": "2 YEAR & Permanent Exclusion-2.pdf", "type": "Waiting Period & Permanent Exclusion Catalog"},
            {"name": "Leaflet artwork.pdf", "type": "Product Brochure & Variant Comparison"},
            {"name": "Mail - ClaimSupport 2.pdf", "type": "Product Feature Email Memo"},
            {"name": "Snapshot.pdf", "type": "Marsh India Market Snapshot & Solvency Ratios"},
        ],
    }
]

# ──────────────────────────────────────────────────────────────────────────────
# 5. Policy Evidence Dataset
# ──────────────────────────────────────────────────────────────────────────────
SEED_EVIDENCES = [
    {
        "evidenceId": "EVID-WP-001",
        "documentName": "2 YEAR & Permanent Exclusion-2.pdf",
        "documentType": "reference_document",
        "pageNumber": 1,
        "sectionHeader": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "textSnippet": "2 YEAR'S SPECIFIC WAITING PERIODS: Cataract, Stones in biliary and urinary systems, Lumps, Cysts, Surgery on tonsils, Arthritis, Rheumatism, Spondylosis, Fissure/Fistula/Haemorrhoids, Hernia/Hydrocele, Sinusitis, Knee/Hip Joint replacement, Varicose veins, Benign Prostate Hypertrophy, Hysterectomy for any benign disorder.",
        "authorityLevel": "REFERENCE_BENCHMARK",
        "tags": ["waiting_period", "2_year", "specific_conditions"],
    },
    {
        "evidenceId": "EVID-EXCL-001",
        "documentName": "2 YEAR & Permanent Exclusion-2.pdf",
        "documentType": "reference_document",
        "pageNumber": 2,
        "sectionHeader": "PERMANENT EXCLUSION - NOT COVERED",
        "textSnippet": "PERMANENT EXCLUSION - NOT COVERED: 1. Investigation & Evaluation, 2. Rest Cure, rehabilitation and respite care, 3. Obesity/Weight Control, 4. Change-of-Gender treatments, 5. Cosmetic or plastic Surgery, 6. Hazardous or Adventure sports, 7. Breach of law, 8. Excluded Providers, 9. Treatment for alcoholism, drug or substance abuse, 10. Heath hydros, nature cure clinics, spas, 11. Dietary supplements without prescription, 12. Refractive Error, 13. Unproven Treatments, 14. Sterility and Infertility, 15. Maternity Expenses, 16. Hospital stay charges not expressly covered, 17. Circumcision, 18. Conflict & Disaster, 19. External Congenital Anomaly, 20. Dental/oral treatment, 21. Hormone Replacement Therapy, 22. Multifocal Lens and home ambulatory devices, 23. STDs (other than HIV/AIDS), 24. Sleep disorders, 25. Medical services outside India, 26. OPD treatment, 27. Unrecognized Physician or Hospital, 28. Stress, relationship, academic problems, work pressure, 29. Intentional self inflicted Injury or attempted suicide, 30. Neuro-developmental delays, 31. Mental retardation, 32. Artificial life maintenance (brain dead).",
        "authorityLevel": "REFERENCE_BENCHMARK",
        "tags": ["permanent_exclusion", "statutory_exclusions", "irda_norm"],
    },
    {
        "evidenceId": "EVID-R3-VARIANTS-001",
        "documentName": "Mail - ClaimSupport 2.pdf",
        "documentType": "reference_document",
        "pageNumber": 3,
        "sectionHeader": "VARIANT COMPARISON",
        "textSnippet": "VARIANT COMPARISON: Classic: General room, Road Ambulance INR 2000, Air Ambulance NA, Modern Treatment INR 1 Lac, Lock Clock No, PA Optional 10L, Daily Cash 1000/day. Select: Twin Sharing room, Road Ambulance Up to SI, Air Ambulance 5L, Modern Treatment Up to SI, Lock Clock Yes, PA Optional 20L, Daily Cash 2000/day, Borderless 10L. Elite: All rooms except Deluxe/Suite, Road Ambulance Up to SI, Air Ambulance 5L, Modern Treatment Up to SI, Lock Clock Yes, PA Optional 50L, Daily Cash 4000/day, Borderless 50L. Black: All rooms, Road Ambulance Up to SI, Air Ambulance 5L, Modern Treatment Up to SI, Lock Clock Yes, PA Optional 1 Cr, Daily Cash 4000/day, Borderless 5 Cr.",
        "authorityLevel": "REFERENCE_BENCHMARK",
        "tags": ["reassure_3", "variant_comparison", "limits"],
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# 6. Specific 2-Year Waiting Period Rules (15 Conditions from Document)
# ──────────────────────────────────────────────────────────────────────────────
SEED_WAITING_PERIOD_RULES = [
    {
        "ruleId": "RULE-WP-CATARACT-001",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Cataract",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24, "waiverRiderAvailable": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Cataract",
        "evidenceId": "EVID-WP-001",
        "keywords": ["cataract", "phacoemulsification", "iol", "intraocular lens", "eye lens replacement", "capsulotomy"],
        "advisoryNotes": "Standard 24-month specific waiting period applies across non-life health policies unless waived by a specific Day 1 rider or continuous policy tenure >= 2 years.",
    },
    {
        "ruleId": "RULE-WP-STONES-002",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Stones in Biliary and Urinary Systems",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Stones in biliary and urinary systems",
        "evidenceId": "EVID-WP-001",
        "keywords": ["gallstone", "cholelithiasis", "kidney stone", "renal calculi", "ureteric calculus", "nephrolithiasis", "lithotripsy", "cholecystectomy", "eswl"],
        "advisoryNotes": "Biliary and urinary calculi surgeries are subject to a 24-month specific waiting period.",
    },
    {
        "ruleId": "RULE-WP-LUMPS-003",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Lumps and Cysts",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Lumps, Cysts",
        "evidenceId": "EVID-WP-001",
        "keywords": ["lump", "cyst", "sebaceous cyst", "ganglion", "dermoid", "lipoma", "excision biopsy"],
        "advisoryNotes": "Benign lumps and cysts have a standard 2-year specific waiting period.",
    },
    {
        "ruleId": "RULE-WP-TONSILS-004",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Surgery on Tonsils / Adenoids",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Surgery on tonsils",
        "evidenceId": "EVID-WP-001",
        "keywords": ["tonsil", "tonsillitis", "tonsillectomy", "adenoid", "adenoidectomy"],
        "advisoryNotes": "Tonsillectomy and adenoid surgery are subject to a 24-month waiting period.",
    },
    {
        "ruleId": "RULE-WP-ARTHRITIS-005",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Arthritis, Rheumatism & Spondylosis",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Arthritis, Rheumatism, Spondylosis",
        "evidenceId": "EVID-WP-001",
        "keywords": ["arthritis", "osteoarthritis", "rheumatoid", "rheumatism", "spondylosis", "cervical spondylosis", "lumbar spondylosis", "slip disc", "sciatica"],
        "advisoryNotes": "Degenerative joint/spinal disorders have a 24-month specific waiting period.",
    },
    {
        "ruleId": "RULE-WP-FISSURE-006",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Fissure, Fistula & Haemorrhoids",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Fissure / Fistula / Haemorrhoids",
        "evidenceId": "EVID-WP-001",
        "keywords": ["fissure", "fistula", "haemorrhoids", "hemorrhoids", "piles", "anal fissure", "fistulectomy", "hemorrhoidectomy"],
        "advisoryNotes": "Anal canal benign disorders are subject to a 24-month waiting period.",
    },
    {
        "ruleId": "RULE-WP-HERNIA-007",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Hernia & Hydrocele",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Hernia / Hydrocele",
        "evidenceId": "EVID-WP-001",
        "keywords": ["hernia", "inguinal hernia", "umbilical hernia", "ventral hernia", "incisional hernia", "herniorrhaphy", "hernioplasty", "hydrocele"],
        "advisoryNotes": "All forms of hernia and hydrocele require 24 months of continuous policy coverage.",
    },
    {
        "ruleId": "RULE-WP-SINUSITIS-008",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Sinusitis & Deviated Nasal Septum",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Sinusitis",
        "evidenceId": "EVID-WP-001",
        "keywords": ["sinusitis", "dns", "septoplasty", "fess", "functional endoscopic sinus surgery"],
        "advisoryNotes": "Sinus surgeries are subject to a 24-month waiting period.",
    },
    {
        "ruleId": "RULE-WP-JOINT-REPLACE-009",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Knee / Hip Joint Replacement",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24, "exceptAccidental": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Knee/Hip Joint replacement",
        "evidenceId": "EVID-WP-001",
        "keywords": ["joint replacement", "knee replacement", "hip replacement", "tkr", "thr", "arthroplasty"],
        "advisoryNotes": "Non-accidental joint replacements carry a 2-year waiting period.",
    },
    {
        "ruleId": "RULE-WP-VARICOSE-010",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Varicose Veins",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Varicose veins",
        "evidenceId": "EVID-WP-001",
        "keywords": ["varicose", "varicose veins", "vein stripping", "endovenous laser", "sclerotherapy"],
        "advisoryNotes": "Treatment of varicose veins and ulceration is subject to a 2-year waiting period.",
    },
    {
        "ruleId": "RULE-WP-BPH-011",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Benign Prostate Hypertrophy (BPH)",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Benign Prostate Hypertrophy",
        "evidenceId": "EVID-WP-001",
        "keywords": ["bph", "prostate", "prostatomegaly", "turp", "transurethral resection"],
        "advisoryNotes": "BPH treatment is subject to a 2-year specific waiting period.",
    },
    {
        "ruleId": "RULE-WP-HYSTERECTOMY-012",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "WAITING_PERIOD",
        "condition": "Benign Hysterectomy & Gynaecological Conditions",
        "decision": "SUBJECT_TO_WAITING_PERIOD",
        "ruleValue": {"waitingPeriodMonths": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 1,
        "sourceSection": "2 YEAR'S SPECIFIC WAITING PERIODS",
        "sourceText": "Hysterectomy for any benign disorder",
        "evidenceId": "EVID-WP-001",
        "keywords": ["hysterectomy", "fibroid", "uterine fibroid", "myomectomy", "endometriosis", "ovarian cystectomy"],
        "advisoryNotes": "Hysterectomy for any benign disorder carries a 24-month waiting period.",
    },
]

# ──────────────────────────────────────────────────────────────────────────────
# 7. 32 Permanent Exclusion Rules (Strictly from Page 2 of Document)
# ──────────────────────────────────────────────────────────────────────────────
RAW_EXCLUSIONS = [
    (1, "Investigation & Evaluation", ["investigation only", "evaluation only", "diagnostic admission", "routine checkup", "check-up only"], "Admission primarily for diagnostic or evaluation purposes is permanently excluded unless leading to inpatient surgical/medical treatment."),
    (2, "Rest Cure, Rehabilitation & Respite Care", ["rest cure", "rehabilitation center", "respite care", "convalescence"], "Expenses related to rest cure, convalescence, rehabilitation, or respite care are permanently excluded."),
    (3, "Obesity / Weight Control", ["obesity", "bariatric", "weight loss", "gastric bypass", "weight control"], "Treatments related to obesity or general weight control are excluded unless severe comorbid criteria are met."),
    (4, "Change-of-Gender Treatments", ["gender reassignment", "gender change", "sex change"], "Medical or surgical interventions for change of gender/sex reassignment are excluded."),
    (5, "Cosmetic or Plastic Surgery", ["cosmetic", "plastic surgery", "rhinoplasty", "aesthetic", "liposuction", "botox"], "Aesthetic, plastic, or cosmetic surgeries are excluded unless reconstructive following accidental injury or burns."),
    (6, "Hazardous or Adventure Sports", ["adventure sports", "skydiving", "scuba diving", "mountaineering", "racing"], "Injuries sustained while participating in hazardous or professional adventure sports are excluded."),
    (7, "Breach of Law", ["criminal act", "breach of law", "illegal activity"], "Expenses arising directly from an intentional criminal act or breach of law are excluded."),
    (8, "Excluded Providers", ["blacklisted hospital", "excluded provider"], "Treatment taken at healthcare providers or hospitals blacklisted by the insurer/IRDAI is non-admissible."),
    (9, "Treatment for Alcoholism & Substance Abuse", ["alcoholism", "drug abuse", "substance abuse", "addiction", "detoxification"], "Treatment for alcohol addiction, narcotic substance abuse, or any addictive condition is permanently excluded."),
    (10, "Treatments in Health Hydros, Spas & Nature Cure", ["nature cure", "spa", "hydrotherapy", "ayurvedic massage spa", "wellness retreat"], "Treatments at health hydros, wellness spas, or nature cure clinics are not covered."),
    (11, "Dietary Supplements Purchased OTC", ["otc supplement", "dietary supplement without prescription", "protein powder", "nutraceutical"], "Dietary and nutritional supplements purchased without physician inpatient prescription are excluded."),
    (12, "Refractive Error (Lasik < 7.5 D)", ["refractive error", "lasik", "prk", "spectacle correction", "contoura"], "Laser refractive surgeries for corrective vision below 7.5 dioptres are excluded."),
    (13, "Unproven & Experimental Treatments", ["unproven", "experimental", "stem cell unauthorized", "clinical trial"], "Experimental or unproven medical therapies lack clinical reimbursement."),
    (14, "Sterility and Infertility", ["infertility", "ivf", "icsi", "surrogacy", "sterility", "tubectomy reversal", "vasectomy reversal"], "Assisted conception, IVF, and sterility management are permanently excluded."),
    (15, "Maternity Expenses (Unless Covered by Rider)", ["maternity", "normal delivery", "caesarean", "c-section", "childbirth", "prenatal", "postnatal"], "Routine childbirth and maternity hospitalizations are excluded unless covered under a dedicated maternity rider."),
    (16, "Charges Related to Hospital Stay Not Expressly Covered", ["admission fee", "registration fee", "service charge", "attendant charge"], "Hospital admission charges, administrative overheads, or attendant comfort fees are non-payable."),
    (17, "Circumcision (Unless for Disease)", ["circumcision", "phimosis circumcision non-medical"], "Routine religious or non-therapeutic circumcisions are excluded."),
    (18, "War, Conflict & Disaster", ["war", "nuclear", "terrorism", "radiation", "civil commotion"], "Injuries resulting from war, invasion, radiation, or catastrophic civil strife are excluded."),
    (19, "External Congenital Anomaly", ["congenital anomaly", "birth defect", "external congenital"], "Congenital external physical anomalies are excluded from claim settlement."),
    (20, "Dental / Oral Treatment", ["dental", "teeth", "tooth extraction", "root canal", "rct", "orthodontic", "dentures"], "Routine dental consultations and tooth restorations are excluded unless requiring emergency hospitalization due to accident."),
    (21, "Hormone Replacement Therapy (HRT)", ["hormone replacement", "hrt"], "Elective or age-related hormonal replacement therapies are not covered."),
    (22, "Multifocal Lens & Home Ambulatory Equipment", ["multifocal lens", "bipap home", "cpap home", "wheelchair", "crutches", "hearing aid"], "Home medical equipment (CPAP, wheelchairs) and premium multifocal intraocular lenses are not reimbursable."),
    (23, "Sexually Transmitted Infections (Except HIV/AIDS)", ["std", "syphilis", "gonorrhea", "chlamydia", "genital herpes"], "Treatment for sexually transmitted infections (other than HIV/AIDS where expressly endorsed) is excluded."),
    (24, "Sleep Disorders", ["sleep apnea", "snoring", "polysomnography sleep disorder"], "Evaluations and surgeries for snoring or sleep apnea are excluded."),
    (25, "Medical Services Outside India", ["treatment abroad", "overseas medical", "foreign hospital"], "Treatments outside India are permanently excluded under standard domestic policies unless Borderless rider is active."),
    (26, "Outpatient (OPD) Treatment", ["opd consultation", "outpatient prescription", "day clinic"], "OPD treatments are excluded unless an OPD/WellConsult rider has been added."),
    (27, "Unrecognized Physician or Hospital", ["unrecognized hospital", "quack", "unlicensed practitioner"], "Treatment by unregistered doctors or unrecognized facilities is permanently barred."),
    (28, "Non-Clinical Stress, Work Pressure & Academic Anxiety", ["work pressure", "academic stress", "relationship difficulties", "acculturation"], "Stress management, relationship counseling, or burnout admissions are non-admissible."),
    (29, "Intentional Self-Inflicted Injury & Attempted Suicide", ["suicide", "self harm", "intentional injury"], "Intentional self-injury or suicide attempts are permanently excluded."),
    (30, "Neuro-developmental Delays & Disorders", ["neurodevelopmental delay", "adhd", "learning disability"], "Developmental delays and cognitive learning disorders are excluded."),
    (31, "Mental Retardation / Intellectual Disability", ["mental retardation", "intellectual disability"], "Treatment for intellectual disability and congenital mental retardation is excluded."),
    (32, "Artificial Life Maintenance (Brain Dead)", ["brain dead", "vegetative state life support"], "Prolonged artificial life support for patients declared clinically brain-dead is excluded once viability is terminal."),
]

SEED_EXCLUSION_RULES = []
for num, name, keywords, notes in RAW_EXCLUSIONS:
    SEED_EXCLUSION_RULES.append({
        "ruleId": f"RULE-EXCL-{num:03d}",
        "insurerName": "All",
        "productName": "Standard Benchmark",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "PERMANENT_EXCLUSION",
        "condition": name,
        "decision": "NOT_COVERED",
        "ruleValue": {"exclusionNumber": num, "permanent": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "2 YEAR & Permanent Exclusion-2.pdf",
        "sourcePage": 2,
        "sourceSection": "PERMANENT EXCLUSION - NOT COVERED",
        "sourceText": f"{num}. {name}",
        "evidenceId": "EVID-EXCL-001",
        "keywords": keywords,
        "advisoryNotes": notes,
    })

# ──────────────────────────────────────────────────────────────────────────────
# 8. ReAssure 3.0 Variant & Benefit Rules (Leaflet artwork & Mail 2)
# ──────────────────────────────────────────────────────────────────────────────
SEED_BENEFIT_RULES = [
    # Room Category Rules across variants
    {
        "ruleId": "RULE-NB-R3-ROOM-CLASSIC",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "Classic",
        "policyVersion": "2026.01",
        "ruleType": "LIMIT",
        "condition": "Room Rent Category",
        "benefitName": "Room Type Covered",
        "decision": "COVERED",
        "ruleValue": {"allowedCategory": "General room", "roomRentCapped": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Classic: General room",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["general room", "room rent limit", "classic room"],
        "advisoryNotes": "Classic variant covers General Room only; higher room tiers may cause proportionate deductions.",
    },
    {
        "ruleId": "RULE-NB-R3-ROOM-SELECT",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "Select",
        "policyVersion": "2026.01",
        "ruleType": "LIMIT",
        "condition": "Room Rent Category",
        "benefitName": "Room Type Covered",
        "decision": "COVERED",
        "ruleValue": {"allowedCategory": "Twin Sharing room", "roomRentCapped": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Select: Twin Sharing room",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["twin sharing", "select room"],
        "advisoryNotes": "Select variant covers Twin Sharing room.",
    },
    {
        "ruleId": "RULE-NB-R3-ROOM-ELITE",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "Elite",
        "policyVersion": "2026.01",
        "ruleType": "LIMIT",
        "condition": "Room Rent Category",
        "benefitName": "Room Type Covered",
        "decision": "COVERED",
        "ruleValue": {"allowedCategory": "All rooms except Deluxe/Suite", "roomRentCapped": False},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Elite: All rooms except Deluxe/Suite",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["single private", "elite room", "all rooms except deluxe"],
        "advisoryNotes": "Elite covers all single private rooms up to full sum insured except Deluxe/Suite rooms.",
    },
    {
        "ruleId": "RULE-NB-R3-ROOM-BLACK",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "Black",
        "policyVersion": "2026.01",
        "ruleType": "LIMIT",
        "condition": "Room Rent Category",
        "benefitName": "Room Type Covered",
        "decision": "COVERED",
        "ruleValue": {"allowedCategory": "All rooms", "roomRentCapped": False, "zeroDeduction": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Black: All rooms",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["all rooms", "deluxe", "suite", "black room"],
        "advisoryNotes": "Black covers any room category without any financial capping or proportionate deduction.",
    },

    # Modern Treatment Limit Rules
    {
        "ruleId": "RULE-NB-R3-MODERN-CLASSIC",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "Classic",
        "policyVersion": "2026.01",
        "ruleType": "SUB_LIMIT",
        "condition": "Modern Treatments",
        "benefitName": "Modern Treatment Limit",
        "decision": "COVERED",
        "ruleValue": {"subLimitINR": 100000, "scope": "Per complete claim amount"},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Classic: Covered up to INR 1 lacs for each complete claim amount.",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["modern treatment", "robotic surgery", "stem cell", "balloon sinuplasty"],
        "advisoryNotes": "In Classic variant, modern treatments (robotic surgeries, stem cell) are capped at INR 1,00,000 per claim.",
    },
    {
        "ruleId": "RULE-NB-R3-MODERN-SELECT-ELITE-BLACK",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "BENEFIT",
        "condition": "Modern Treatments",
        "benefitName": "Modern Treatment Limit",
        "decision": "COVERED",
        "ruleValue": {"limit": "Up to Sum Insured", "noSubLimit": True},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Select/Elite/Black: Up to Sum Insured",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["modern treatment", "robotic surgery", "stem cell", "balloon sinuplasty"],
        "advisoryNotes": "Modern treatments covered up to full Sum Insured in Select, Elite, and Black plans.",
    },

    # Air Ambulance Rules
    {
        "ruleId": "RULE-NB-R3-AIR-AMBULANCE",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "SUB_LIMIT",
        "condition": "Air Ambulance Coverage",
        "benefitName": "Expenses in Reaching the Hospital",
        "decision": "COVERED",
        "ruleValue": {"limitINR": 500000, "perHospitalization": True, "classicCovered": False},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Air Ambulance: INR 5L Per Hospitalization (Select/Elite/Black), NA for Classic",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["air ambulance", "emergency airlift", "helicopter transfer"],
        "advisoryNotes": "Air ambulance covered up to INR 5,00,000 per hospitalization in Select, Elite, and Black tiers.",
    },

    # Hospitalization Requirement Rule (2+ Hours)
    {
        "ruleId": "RULE-NB-R3-HOSP-HOURS",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "HOSPITALIZATION_REQUIREMENT",
        "condition": "Minimum Hospitalization Duration",
        "benefitName": "Hospitalization Hours",
        "decision": "COVERED",
        "ruleValue": {"minAllopathicHours": 2, "minAYUSHHours": 24},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 4,
        "sourceSection": "INDUSTRY COMPARISON",
        "sourceText": "Allows you to get coverage for all hospitalizations lasting more than 2 hours (AYUSH 24+ hours).",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["2 hours hospitalization", "day care", "short stay", "ayush"],
        "advisoryNotes": "ReAssure 3.0 requires only 2+ hours of hospitalization for allopathic daycare procedures vs industry standard 24 hours.",
    },

    # Consumables Coverage Rule (Claim Safeguard+)
    {
        "ruleId": "RULE-NB-R3-CONSUMABLES",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "BENEFIT",
        "condition": "Non-Payable Items & Consumables",
        "benefitName": "Claim Safeguard+",
        "decision": "COVERED",
        "ruleValue": {"coveredLists": ["List I", "List II", "List III", "List IV"], "reimbursementPct": 100},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 4,
        "sourceSection": "INDUSTRY COMPARISON",
        "sourceText": "NON-PAYABLE ITEMS ARE COVERED: All 4 non-payable item lists covered under Claim Safeguard+.",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["consumables", "gloves", "ppe", "syringes", "safeguard", "non-medical items"],
        "advisoryNotes": "100% reimbursement for non-payable hospital consumables (IRDAI Lists I to IV) included under Claim Safeguard+.",
    },

    # Pre & Post Hospitalization Days
    {
        "ruleId": "RULE-NB-R3-PRE-POST",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "BENEFIT",
        "condition": "Pre and Post Hospitalization Medical Expenses",
        "benefitName": "Pre & Post Hospitalization Window",
        "decision": "COVERED",
        "ruleValue": {"preHospitalizationDays": 60, "postHospitalizationDays": 180},
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Leaflet artwork.pdf",
        "sourcePage": 1,
        "sourceSection": "BENEFITS",
        "sourceText": "Pre-hospitalization: 60 days, Post-hospitalization: 180 days.",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["pre hospitalization", "post hospitalization", "discharge follow-up"],
        "advisoryNotes": "Provides 60 days pre-admission and 180 days post-discharge diagnostic and medicine coverage.",
    },

    # Global Treatment (Borderless)
    {
        "ruleId": "RULE-NB-R3-BORDERLESS",
        "insurerName": "Niva Bupa Health Insurance Company Limited",
        "productName": "ReAssure 3.0",
        "variantName": "All",
        "policyVersion": "2026.01",
        "ruleType": "GEOGRAPHICAL_RESTRICTION",
        "condition": "Treatment Outside India (Borderless)",
        "benefitName": "Borderless Global Treatment",
        "decision": "CONDITIONAL",
        "ruleValue": {
            "Classic": "NA",
            "Select": "Up to INR 10 Lacs",
            "Elite": "Up to INR 50 Lacs",
            "Black": "Up to INR 5 Crore",
            "copayPct": 0,
        },
        "effectiveFrom": NOW_UTC,
        "isActive": True,
        "authorityLevel": "REFERENCE_BENCHMARK",
        "sourceDocument": "Mail - ClaimSupport 2.pdf",
        "sourcePage": 3,
        "sourceSection": "VARIANT COMPARISON",
        "sourceText": "Borderless: NA (Classic), 10L (Select), 50L (Elite), 5 Cr (Black). 0% co-pay.",
        "evidenceId": "EVID-R3-VARIANTS-001",
        "keywords": ["borderless", "global treatment", "treatment abroad", "overseas hospitalization"],
        "advisoryNotes": "Optional global cover with 0% co-pay available on Select (10L), Elite (50L), and Black (5 Cr). Classic has no borderless option.",
    },
]

ALL_SEED_RULES = SEED_WAITING_PERIOD_RULES + SEED_EXCLUSION_RULES + SEED_BENEFIT_RULES
